SET NAMES utf8mb4;

CREATE DATABASE IF NOT EXISTS sample_api;

USE sample_api;

CREATE TABLE IF NOT EXISTS product (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO product (name, price) VALUES ('Product 1', 10.99);
INSERT INTO product (name, price) VALUES ('Product 2', 20.99);
INSERT INTO product (name, price) VALUES ('Product 3', 30.99);